import Link from "next/link";

export const metadata = {
  title: "The unsupervised landscape — Manifold",
  description:
    "Clustering is one part of unsupervised learning — finding structure in unlabelled data. This is the map: what unsupervised learning is, what its main tasks are, and where k-means sits.",
};

export default function LandscapePage() {
  return (
    <article>
      <div style={{ display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center", marginBottom: 12 }}>
        <span style={chip("var(--c-clustering)")}>Clustering</span>
        <span style={{ fontSize: 12, color: "var(--faint)" }}>· about 5 minutes</span>
      </div>

      <h1 className="font-serif" style={{ fontSize: 40, lineHeight: 1.1, letterSpacing: "-0.01em", margin: "0 0 8px", color: "var(--ink)" }}>
        The unsupervised landscape
      </h1>
      <p style={{ fontSize: 17, color: "var(--muted)", lineHeight: 1.6, margin: "0 0 24px", maxWidth: 620 }}>
        Before diving into k-means, it helps to see the territory it lives in. Clustering is one task
        inside <strong>unsupervised learning</strong> — the branch of ML that finds structure with no
        answer key.
      </p>

      <div className="lesson">
        <h2>Learning without labels</h2>
        <p>
          In <strong>supervised</strong> learning (linear regression, classification) every example comes
          with a target, and the model learns to predict it. <strong>Unsupervised</strong> learning has{" "}
          <em>no</em> targets — just the data itself. The goal shifts from &ldquo;predict <em>y</em>&rdquo; to
          &ldquo;reveal the hidden structure in <em>X</em>.&rdquo; That difference is everything: there&rsquo;s no
          accuracy to optimise and no ground truth to check against, so success is judged by whether the
          structure you find is <em>useful</em>.
        </p>

        <h2>The main unsupervised tasks</h2>
        <ul style={ul}>
          <li>
            <strong>Clustering</strong> — group similar items together (customers, documents, pixels).
            k-means lives here. The output is a label per item saying which group it&rsquo;s in.
          </li>
          <li>
            <strong>Dimensionality reduction</strong> — compress many features into a few while keeping the
            important variation (PCA, UMAP, autoencoders). Often a <em>precursor</em> to clustering.
          </li>
          <li>
            <strong>Density estimation</strong> — model where the data is dense vs. sparse, and generate new
            samples (Gaussian mixtures, normalising flows).
          </li>
          <li>
            <strong>Anomaly detection</strong> — find the points that <em>don&rsquo;t</em> fit the structure
            (fraud, defects, outliers).
          </li>
          <li>
            <strong>Association / representation learning</strong> — find co-occurrence rules, or learn
            embeddings that make downstream tasks easier.
          </li>
        </ul>

        <h2>Where clustering itself splits</h2>
        <p>
          Even within clustering there are distinct philosophies — worth knowing so you recognise when
          k-means is the wrong family member:
        </p>
        <ul style={ul}>
          <li><strong>Partitional</strong> (k-means, k-medoids): split data into a flat set of <em>k</em> groups.</li>
          <li><strong>Hierarchical</strong>: build a tree of nested clusters you can cut at any level.</li>
          <li><strong>Density-based</strong> (DBSCAN): grow clusters through dense regions, label sparse points as noise.</li>
          <li><strong>Model-based</strong> (Gaussian mixtures): assume the data is generated by a mixture of distributions and fit it.</li>
        </ul>

        <div style={callout}>
          <div className="font-display" style={{ fontSize: 13, fontWeight: 500, color: "var(--c-clustering)", marginBottom: 4 }}>
            Why start with k-means
          </div>
          <p style={{ margin: 0, color: "var(--muted)", fontSize: 14.5, lineHeight: 1.6 }}>
            k-Means is the canonical partitional clustering algorithm: simple enough to understand
            completely, fast enough to use at scale, and a gateway to nearly every other method (GMM, DBSCAN,
            hierarchical, and the whole variant family) by contrast. Master it and the rest of the
            unsupervised landscape becomes far easier to navigate — most other methods are best understood
            as &ldquo;k-means, but relaxing <em>this</em> assumption.&rdquo;
          </p>
        </div>

        <p>
          One concept underlies essentially all of clustering: a notion of how <em>similar</em> two items
          are. That&rsquo;s the next page.
        </p>

        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 40, paddingTop: 16, borderTop: "1px solid var(--border)" }}>
          <Link href="/learn/k-means" style={navLink}>← What is clustering?</Link>
          <Link href="/learn/k-means/similarity-and-distance" style={{ ...navLink, fontWeight: 600 }}>Next up · Similarity &amp; distance →</Link>
        </div>
      </div>
    </article>
  );
}

function chip(color: string): React.CSSProperties {
  return { display: "inline-flex", alignItems: "center", background: `color-mix(in srgb, ${color} 13%, var(--surface))`, color, fontSize: 12, padding: "3px 10px", borderRadius: 999 };
}
const ul: React.CSSProperties = { margin: "0 0 10px", paddingLeft: "1.3em", fontSize: 15, color: "var(--muted)", lineHeight: 1.8 };
const navLink: React.CSSProperties = { fontSize: 14, color: "var(--brand)", textDecoration: "none" };
const callout: React.CSSProperties = { background: "color-mix(in srgb, var(--c-clustering) 9%, var(--surface))", border: "1px solid color-mix(in srgb, var(--c-clustering) 22%, var(--border))", borderRadius: 12, padding: "13px 15px", margin: "1.8rem 0" };
